stages:
    - tests

tests:
    image: git.jinr.ru:5005/gna/gna-base-docker-image:latest
    stage: tests

    script:
    - python3 -m pip install -r requirements.txt
    - coverage run --source=. --omit=subtrees/* -m pytest
    - coverage report
    - coverage xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        paths:
            - test/output
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
    only:
        - master
        - update-to-data-preservation
        - merge_requests
